// actionTypes.js
export const LIKE_BLOG_REQUEST = "LIKE_BLOG_REQUEST";
export const LIKE_BLOG_SUCCESS = "LIKE_BLOG_SUCCESS";
export const LIKE_BLOG_FAILURE = "LIKE_BLOG_FAILURE";

export const BOOKMARK_BLOG_REQUEST = "BOOKMARK_BLOG_REQUEST";
export const BOOKMARK_BLOG_SUCCESS = "BOOKMARK_BLOG_SUCCESS";
export const BOOKMARK_BLOG_FAILURE = "BOOKMARK_BLOG_FAILURE";
